services:
  mysql:
    container_name: mysql
    image: mysql:9.1
    ports:
      - "3306:3306"
    networks:
      - data
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_DATABASE=almacen
      - MYSQL_USER=mysql_agent
      - MYSQL_PASSWORD=1234
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
networks:
  data:
    driver: bridge